---
# Docker Hub Image Pull Secret for Private Repository
# This secret is required to pull images from private Docker Hub repositories
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: healthcare-api
type: kubernetes.io/dockerconfigjson
data:
  # This will be populated when you create the secret using kubectl
  # Do not manually edit this field
  .dockerconfigjson: ""

---
# Instructions to create this secret:
# 
# Method 1: Using kubectl command (Recommended)
# kubectl create secret docker-registry dockerhub-secret \
#   --docker-server=docker.io \
#   --docker-username=YOUR_DOCKERHUB_USERNAME \
#   --docker-password=YOUR_DOCKERHUB_TOKEN \
#   --namespace=healthcare-api
#
# Method 2: From existing Docker config
# kubectl create secret generic dockerhub-secret \
#   --from-file=.dockerconfigjson=$HOME/.docker/config.json \
#   --type=kubernetes.io/dockerconfigjson \
#   --namespace=healthcare-api
#
# Method 3: Apply this file after base64 encoding your Docker config
# 1. Create .dockerconfigjson content:
#    {
#      "auths": {
#        "docker.io": {
#          "username": "YOUR_USERNAME",
#          "password": "YOUR_TOKEN",
#          "auth": "BASE64_ENCODED_USERNAME:PASSWORD"
#        }
#      }
#    }
# 2. Base64 encode the JSON and replace the .dockerconfigjson field above
# 3. kubectl apply -f this-file.yaml