# Docker Hub Credentials External Secret Configuration
# This will sync Docker Hub credentials from AWS Secrets Manager

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dockerhub-external-secret
  namespace: healthcare-api
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore
  target:
    name: dockerhub-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "docker.io": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
  - secretKey: username
    remoteRef:
      key: poc-docker
      property: username
  - secretKey: password
    remoteRef:
      key: poc-docker
      property: password

---
# Alternative: ClusterSecretStore for cluster-wide access
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager-cluster-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets-system